---
# ---------------------------------------------------------------------------- #
# basic
# ---------------------------------------------------------------------------- #
name : 'trus_unet3d_DDP_Sybn_crop128_bs1x8_ch32_kaiming_dc_adam_1e-4_step_0.2_warmup_10_1e-5'
dataset_name : 'trus'
model_name : 'unet3d'
test_name : 'crop128_slide32_nopad_noaug'
visible_gpu : !!str "'0,''1,''2,''3,''4,''5,''6,''7'"
local_gpu : 7
gpu_ids : [0,1]
phase_list : ['test', 'val']
DEBUG : False
deterministic : True

phase : 'val'
batch_size : 2
no_augment : True
compute_pad : False
save_visuals : False
# ---------------------------------------------------------------------------- #
# weights
# ---------------------------------------------------------------------------- #
weight_path : './traces/checkpoints/trus_unet3d_DDP_Sybn_crop128_bs1x8_ch32_kaiming_dc_adam_1e-4_step_0.2_warmup_10_1e-5/65_net_trus_unet3d_DDP_SynBN_crop128_bs3x4_ch32_dc_adam_1e-4.pth'
verbose : false
weight_dir  : './traces/checkpoints/trus_unet3d_DDP_Sybn_crop128_bs1x8_ch32_kaiming_dc_adam_1e-4_step_0.2_warmup_10_1e-5'
weight_on_dir : True

logs_dir : './traces/logs'
checkpoints_dir : './traces/checkpoints'
results_dir : './traces/results'

# dataset
dataroot : './traces/datasets/prostate_daf3d_pre'
crop_size : [128, 128, 128]
target_size : [128, 128, 128]
stride : [32, 32, 32]




# dataloader
num_threads : 8


# ---------------------------------------------------------------------------- #
# module
# ---------------------------------------------------------------------------- #
# model
input_nc : 1
output_nc : 1
init_channel_number : 32
up_interpolate : False
conv_order : 'crb'

# ---------------------------------------------------------------------------- #
# test
# ---------------------------------------------------------------------------- #
eval : True
metric_names : ['dice', 'recall', 'precision', 'accuracy']
visual_names : ['segment', 'label', 'pad_volume']


# 'basic_metrics',
...

